on:
  push:
    branches:
      - users/kapasrij/release1.0.7

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # install dependencies, build, and test
    - name: npm install, build, and test
      working-directory: .
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: anchauhWinWebApp
        package: .
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}